# Generated by Django 4.1.2 on 2022-10-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='excerpt',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
