# Generated by Django 4.1.2 on 2022-10-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogauthorsorderable'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogauthor',
            name='bio',
            field=models.CharField(default='No Bio', max_length=255),
            preserve_default=False,
        ),
    ]
