# Generated by Django 4.1.2 on 2022-10-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpagetag_remove_blogpage_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog'},
        ),
    ]
