# Generated by Django 4.1.2 on 2022-10-13 17:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
