# Generated by Django 4.1.2 on 2022-10-13 17:35

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_call_to_action_remove_homepage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
