# Generated by Django 4.1.2 on 2022-10-13 20:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_homepage_hero_text_homepage_hero_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_banner',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock()), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
