# Generated by Django 4.1.2 on 2022-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepage_hero_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_posts_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
