# Generated by Django 4.1.2 on 2022-10-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_featured_posts_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='featured_posts_title',
            new_name='featured_blogs_title',
        ),
    ]
