# Generated by Django 4.1.2 on 2022-10-19 10:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_featured_posts_title_homepage_featured_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_banner',
            field=wagtail.fields.StreamField([('subheading', wagtail.blocks.CharBlock()), ('content', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
